services:
  mongo:
    image: mongo:7
    container_name: proshop-mongo
    ports:
      - "27017:27017"
    volumes:
      - proshop_mongo_data:/data/db
    restart: unless-stopped

volumes:
  proshop_mongo_data:
